### ISSUE TITLE
Programes of the Schedule in alphabetical order

### ISSUE THREAD

**Issue by beaulalume** [iago1460/django-radio#20]
When you programe the schedule, the programs on the left column appear in chronological order (first ones are the last ones we add to RadioCo).  Now we have 50 programs, and it´s difficult to find the one we are looking for. It would be much easier if the programes where in alphabetical order. Or even to have a Search tool.

**Comment by txenoo** [comment]
I think that this would be a nice to have feature, another improvement in the schedule would be not showing shows whose finish date is earlier than the beginning of the schedule. In this way you would make easy to program because old shows would not appear.

In this case the scheduling should reload the program list each time the schedule sheet is changed.

**Comment by iago1460** [comment]
For now, added order by name to programmes
